/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructura.FilaPacientes;
import Estructura.ListaConsultorios;
import static Interfaz.Ingresos.FichasV;
import Interfaz.Inicio;
import modelo.enums.CategoriasEstructura;
import ServicioEmergencia.ServicioConsultorios;
import javax.swing.JOptionPane;

/**
 *
 * @author marip
 */
public class Administracion extends javax.swing.JFrame {
        int FichasV, FichasA, FichasR, PromedioA, PromedioV,PromedioR;
        
    /**
     * Creates new form Principal
     */
    public Administracion() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //total pacientes
        FichasV = Ingresos.FichasV;
        FichasA = Ingresos.FichasA;
        FichasR = Ingresos.FichasR;
       
        lblVerdes.setText("" + FichasV);
        lblAmarillos.setText("" + FichasA);
        lblRojos.setText("" + FichasR);
        
        //Promedio Consultorios
        PromedioA = ConsAmarillo.promedioA / ConsAmarillo.contadorA;
        PromedioV = ConsVerde.promedioV / ConsVerde.contadorV;
        PromedioR = ConsRojo.promedioR / ConsRojo.contadorR;
        
        lblPA.setText("" + PromedioA);
        lblPV.setText("" + PromedioV);
        lblPR.setText("" + PromedioR);
        
        
        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVerde = new javax.swing.JLabel();
        lblAmarillo = new javax.swing.JLabel();
        lblRojo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnActivos = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        lblR = new javax.swing.JLabel();
        lblRojos = new javax.swing.JLabel();
        lblV = new javax.swing.JLabel();
        lblVerdes = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblAmarillos = new javax.swing.JLabel();
        gf = new javax.swing.JLabel();
        gf1 = new javax.swing.JLabel();
        gf2 = new javax.swing.JLabel();
        lblPV = new javax.swing.JLabel();
        lblPR = new javax.swing.JLabel();
        gf3 = new javax.swing.JLabel();
        lblPA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerde.setText("Consultorios Verdes:");
        getContentPane().add(lblVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 40));

        lblAmarillo.setText("Consultorios Amarillos:");
        getContentPane().add(lblAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblRojo.setText("Consultorios Rojos:");
        getContentPane().add(lblRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        lblTitulo.setText("Administración");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 22, -1, -1));

        jLabel1.setText("Promedio Egresos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 454, -1, -1));

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel5.setText("Tipo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel7.setText("Tipo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 454, -1, -1));

        jLabel8.setText("Tipo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        btnActivos.setText("Modificar consultorios activos");
        btnActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivosActionPerformed(evt);
            }
        });
        getContentPane().add(btnActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        btnEstado.setText("Mostrar estado consultorios");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        lblR.setText("Total de pacientes Rojos:");
        getContentPane().add(lblR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblRojos.setText("0");
        getContentPane().add(lblRojos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        lblV.setText("Total de pacientes Verdes:");
        getContentPane().add(lblV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblVerdes.setText("0");
        getContentPane().add(lblVerdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 70, 10, -1));

        lblA.setText("Total de pacientes Amarillos:");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblAmarillos.setText("0");
        getContentPane().add(lblAmarillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        gf.setText("Promedio Tiempo Espera:");
        getContentPane().add(gf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        gf1.setText("Promedio Tiempo Espera:");
        getContentPane().add(gf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        gf2.setText("Promedio Tiempo Espera:");
        getContentPane().add(gf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        lblPV.setText("0");
        getContentPane().add(lblPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        lblPR.setText("0");
        getContentPane().add(lblPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        gf3.setText("Promedio Tiempo Espera:");
        getContentPane().add(gf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        lblPA.setText("0");
        getContentPane().add(lblPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivosActionPerformed
         ModificarActivos activos = new ModificarActivos();
        activos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActivosActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        MostrarEstado estado = new MostrarEstado();
        estado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstadoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivos;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel gf;
    private javax.swing.JLabel gf1;
    private javax.swing.JLabel gf2;
    private javax.swing.JLabel gf3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAmarillo;
    private javax.swing.JLabel lblAmarillos;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPR;
    private javax.swing.JLabel lblPV;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JLabel lblRojos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblV;
    private javax.swing.JLabel lblVerde;
    private javax.swing.JLabel lblVerdes;
    // End of variables declaration//GEN-END:variables
}
