/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructura.Pacientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevca
 */
public class ConsRojo extends javax.swing.JFrame {
    
    int dato = ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getCantConsultoriosActivos();
    
    public ConsRojo() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero del consultorio");
        modelo.addColumn("Condicion del consultorio");
        for(int i = 1;i<=dato;i++){
            modelo.addRow(new Object[]{i, ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[i].getEstado()});
        }
        tabla_rojos.setModel(modelo);
    }
    
    public void actualizarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero del consultorio");
        modelo.addColumn("Condicion del consultorio");
        for(int i = 1;i<=dato;i++){
            modelo.addRow(new Object[]{i, ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[i].getEstado()});
        }
        tabla_rojos.setModel(modelo);
        modelo.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_rojos = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtender = new javax.swing.JButton();
        btnLiberarAtender = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_rojos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_rojos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 470, 340));

        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Consultorios Rojos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel2.setText("Seleccione el consultorio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        btnAtender.setText("Atender");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        btnLiberarAtender.setText("Liberar y Antender");
        btnLiberarAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarAtenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnLiberarAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        DefaultTableModel model = (DefaultTableModel)tabla_rojos.getModel();
        int indice = tabla_rojos.getSelectedRow();//para obtener la fila seleccionada
        indice++;
        Pacientes paciente = ServicioEmergencia.Filas.filaRoja.nextPaciente();
        if ((paciente == null) || ( ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].getEstado() == "Ocupado")){//falta ver como validar
            JOptionPane.showMessageDialog(null, "No hay más pacientes por atender o el consultorio no esta libre");
        }else{
            //hacer hora salida
            //duracion
            ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].atenderSigPaciente(paciente);
            ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].setEstado("Ocupado");
            JOptionPane.showMessageDialog(null, "Atendiendo paciente " + paciente.getFicha() + "en consultorio #" + indice );
        }
        actualizarTabla();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnLiberarAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarAtenderActionPerformed
                DefaultTableModel model = (DefaultTableModel)tabla_rojos.getModel();
        int indice = tabla_rojos.getSelectedRow();//para obtener la fila seleccionada
        indice++; //aumentamos en 1 por que el arreglo empieza en 0
        Pacientes sigPaciente = ServicioEmergencia.Filas.filaRoja.nextPaciente();
        if (ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].getEstado() == "Ocupado"){
            Pacientes pacienteEgresos = ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].getPacienteAtendiendo();
            ServicioEmergencia.Filas.filaEgresos.insertPaciente(pacienteEgresos);
            JOptionPane.showMessageDialog(null, "Paciente " + pacienteEgresos.getFicha() + "ha pasado a la fila de Egresos");
            if (sigPaciente == null) {//falta ver como validar
                ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].setEstado("Libre");
                JOptionPane.showMessageDialog(null, "No hay más pacientes por atender");
            }else{
            //hacer hora salida
            //duracion
                ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].atenderSigPaciente(sigPaciente);
                ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getConsultorios()[indice].setEstado("Ocupado");
                JOptionPane.showMessageDialog(null, "Atendiendo paciente " + sigPaciente.getFicha() + "en consultorio #" + indice );
        }
        }else{JOptionPane.showMessageDialog(null, "Presiona Atender" );}
        actualizarTabla();
    }//GEN-LAST:event_btnLiberarAtenderActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnLiberarAtender;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_rojos;
    // End of variables declaration//GEN-END:variables
}
