/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructura.Pacientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author marip
 */
public class Egresos extends javax.swing.JFrame {
    public static double promedioE;
    public static int contadorE;
    int dato = ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getCantConsultoriosActivos();

    /**
     * Creates new form Egresos
     */
    public Egresos() {
        contadorE = 0;
        promedioE = 0;
       initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero del puesto de atencion");
        modelo.addColumn("Condicion del puesto de atención");
        for(int i = 1;i<=dato;i++){
            modelo.addRow(new Object[]{i, ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[i].getEstado()});
        }
        tabla_egresos.setModel(modelo);
    }
    public void actualizarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero del puesto de atencion");
        modelo.addColumn("Condicion del puesto de atención");
        for(int i = 1;i<=dato;i++){
            modelo.addRow(new Object[]{i, ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[i].getEstado()});
        }
        tabla_egresos.setModel(modelo);
        modelo.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEgresos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_egresos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnRelease = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEgresos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblEgresos.setForeground(new java.awt.Color(255, 255, 255));
        lblEgresos.setText("Egresos");
        getContentPane().add(lblEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 35, -1, -1));

        tabla_egresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_egresos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 72, 451, 347));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.setForeground(new java.awt.Color(153, 0, 0));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        btnRelease.setBackground(new java.awt.Color(255, 255, 255));
        btnRelease.setForeground(new java.awt.Color(153, 0, 0));
        btnRelease.setText("Dar de alta");
        btnRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReleaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelease, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        btnAtender.setBackground(new java.awt.Color(255, 255, 255));
        btnAtender.setForeground(new java.awt.Color(153, 0, 0));
        btnAtender.setText("Atender ");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed

        DefaultTableModel model = (DefaultTableModel)tabla_egresos.getModel();
        int indice = tabla_egresos.getSelectedRow();//para obtener la fila seleccionada
        indice++;
        Pacientes paciente = ServicioEmergencia.Filas.filaEgresos.nextPaciente();
        if ((paciente == null) || ( ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[indice].getEstado() == "Ocupado")){//falta ver como validar
            JOptionPane.showMessageDialog(null, "No hay más pacientes por atender o el puesto no esta libre");
        }else{
            contadorE ++;
            double random = (Math.random() * (ServicioEmergencia.Filas.maxEgresos - ServicioEmergencia.Filas.minEgresos) 
                + ServicioEmergencia.Filas.minEgresos);
            
            promedioE = promedioE + random;
            
            ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[indice].atenderSigPaciente(paciente);
            ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[indice].setEstado("Ocupado");
            JOptionPane.showMessageDialog(null, "Atendiendo paciente " + paciente.getFicha() + "en puesto #" + indice + ". Su tiempo en la fila de espera"
                    + "fue de "+ random + " segundos");
        }
        actualizarTabla();
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReleaseActionPerformed
        int indice = tabla_egresos.getSelectedRow();//para obtener la fila seleccionada
        indice++;
        Pacientes pacienteAlta = ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[indice].getPacienteAtendiendo();
        ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getConsultorios()[indice].setEstado("Libre");
        JOptionPane.showMessageDialog(null, "Encuesta de servicio para el paciente " + pacienteAlta.getFicha());
        actualizarTabla();
    }//GEN-LAST:event_btnReleaseActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRelease;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEgresos;
    private javax.swing.JTable tabla_egresos;
    // End of variables declaration//GEN-END:variables
}
