/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Interfaz.Ingresos;

/**
 *
 * @author marip
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresos = new javax.swing.JButton();
        btnEgresos = new javax.swing.JButton();
        btnUrgencias = new javax.swing.JButton();
        btnEmergencias = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresos.setBackground(new java.awt.Color(204, 0, 0));
        btnIngresos.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresos.setText("Ingresos");
        btnIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresosMouseClicked(evt);
            }
        });
        getContentPane().add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        btnEgresos.setBackground(new java.awt.Color(204, 0, 0));
        btnEgresos.setForeground(new java.awt.Color(255, 255, 255));
        btnEgresos.setText("Egresos");
        getContentPane().add(btnEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        btnUrgencias.setBackground(new java.awt.Color(204, 0, 0));
        btnUrgencias.setForeground(new java.awt.Color(255, 255, 255));
        btnUrgencias.setText("Urgencias");
        getContentPane().add(btnUrgencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        btnEmergencias.setBackground(new java.awt.Color(204, 0, 0));
        btnEmergencias.setForeground(new java.awt.Color(255, 255, 255));
        btnEmergencias.setText("Emergencias");
        getContentPane().add(btnEmergencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        btnAdministrador.setBackground(new java.awt.Color(204, 0, 0));
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrador.setText("Administrador");
        getContentPane().add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        lblFondo.setBackground(new java.awt.Color(255, 255, 255));
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 360, 280));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresosMouseClicked
       Ingresos ingreso = new Ingresos();
       ingreso.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnIngresosMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnEgresos;
    private javax.swing.JButton btnEmergencias;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnUrgencias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
