/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author marip
 */
public class ModificarActivos extends javax.swing.JFrame {

    /**
     * Creates new form ModificarActivos
     */
    public ModificarActivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVerde = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtVerdes = new javax.swing.JTextField();
        txtAmarillos = new javax.swing.JTextField();
        txtRojos = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtEgresos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVerde.setText("Verdes");

        lbl.setText("Amarillos");

        lbl1.setText("Rojos");

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnMenu.setMnemonic('M');
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultorios/Puestos de atención que quedarán activos");

        lbl2.setText("Egresos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnContinuar)
                                .addGap(34, 34, 34)
                                .addComponent(btnMenu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAmarillos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVerde)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lbl2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtEgresos))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lbl1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtRojos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerde)
                    .addComponent(txtVerdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(txtAmarillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(txtRojos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(txtEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnMenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        JOptionPane.showMessageDialog(null, "Se liberarán todos los pacientes en los consultorios a desactivar");
        if (this.txtVerdes.getText().isEmpty() == false) {
           int verdes = Integer.parseInt(txtVerdes.getText());
            if (verdes <= ServicioEmergencia.ServicioConsultorios.consultoriosVerdes.getCantTotalConsultorios()){
                ServicioEmergencia.ServicioConsultorios.consultoriosVerdes.setCantConsultoriosActivos(verdes);
                JOptionPane.showMessageDialog(null, "Se han desactivado exitosamente los consultorios Verdes");
            }else{JOptionPane.showMessageDialog(null, "La cantidad de consultorios verdes que quedaran activos no puede ser mayor a las cantidad"
                    + "total de consultorios");}
       if (this.txtAmarillos.getText().isEmpty() == false) {
           int amarillos = Integer.parseInt(txtAmarillos.getText());
            if (amarillos <= ServicioEmergencia.ServicioConsultorios.consultoriosAmarillos.getCantTotalConsultorios()){
                ServicioEmergencia.ServicioConsultorios.consultoriosAmarillos.setCantConsultoriosActivos(amarillos);
                 JOptionPane.showMessageDialog(null, "Se han desactivado exitosamente los consultorios Amarillos");
            }else{JOptionPane.showMessageDialog(null, "La cantidad de consultorios amarillos que quedaran activos no puede ser mayor a las cantidad"
                    + " total de consultorios");}
            
        } if (this.txtRojos.getText().isEmpty() == false ) {
            int rojo = Integer.parseInt(txtRojos.getText());
            if (rojo <= ServicioEmergencia.ServicioConsultorios.consultoriosRojos.getCantTotalConsultorios()){
                ServicioEmergencia.ServicioConsultorios.consultoriosRojos.setCantConsultoriosActivos(rojo);
                 JOptionPane.showMessageDialog(null, "Se han desactivado exitosamente los consultorios Rojos");
            }else{JOptionPane.showMessageDialog(null, "La cantidad de consultorios rojos que quedaran activos no puede ser mayor a las cantidad"
                    + "total de consultorios");}
        }
        } else if (this.txtEgresos.getText().isEmpty() == false){
            if (Integer.parseInt(txtEgresos.getText()) <= ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.getCantTotalConsultorios()){
                ServicioEmergencia.ServicioConsultorios.consultoriosEgresos.setCantConsultoriosActivos(Integer.parseInt(txtEgresos.getText()));
                 JOptionPane.showMessageDialog(null, "Se han desactivado exitosamente los puestos de Egresos");
            }else{JOptionPane.showMessageDialog(null, "La cantidad de puestos de atencion que quedaran activos no puede ser mayor a las cantidad"
                    + "total de consultorios");}
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Administracion menu = new Administracion();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblVerde;
    private javax.swing.JTextField txtAmarillos;
    private javax.swing.JTextField txtEgresos;
    private javax.swing.JTextField txtRojos;
    private javax.swing.JTextField txtVerdes;
    // End of variables declaration//GEN-END:variables
}
