/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructura.FilaPacientes;
import Estructura.ListaConsultorios;
import Interfaz.Inicio;
import modelo.enums.CategoriasEstructura;
import ServicioEmergencia.ServicioConsultorios;
import javax.swing.JOptionPane;

/**
 *
 * @author marip
 */
public class Principal extends javax.swing.JFrame {

    public static String tipoV, tipoA, tipoR, tipoE;
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVerde = new javax.swing.JLabel();
        lblAmarillo = new javax.swing.JLabel();
        lblRojo = new javax.swing.JLabel();
        txtVerde = new javax.swing.JTextField();
        txtAmarillo = new javax.swing.JTextField();
        txtRojo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        comboAmarillo = new javax.swing.JComboBox<>();
        comboVerde = new javax.swing.JComboBox<>();
        comboEgresos = new javax.swing.JComboBox<>();
        btnContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboRojo1 = new javax.swing.JComboBox<>();
        txtMinEgresos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaxEgresos = new javax.swing.JTextField();
        txtEgresos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVerde.setText("Consultorios Verdes:");
        getContentPane().add(lblVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 58, -1, -1));

        lblAmarillo.setText("Consultorios Amarillos:");
        getContentPane().add(lblAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 105, -1, -1));

        lblRojo.setText("Consultorios Rojos:");
        getContentPane().add(lblRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 164, -1, -1));
        getContentPane().add(txtVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 55, 63, -1));
        getContentPane().add(txtAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 102, 56, -1));
        getContentPane().add(txtRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 161, 58, -1));

        lblTitulo.setText("Configuración Inicial");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 17, -1, -1));

        comboAmarillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEAP", "COLA", " " }));
        getContentPane().add(comboAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 102, -1, -1));

        comboVerde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEAP", "COLA", " " }));
        getContentPane().add(comboVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 55, -1, -1));

        comboEgresos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEAP", "COLA", " " }));
        getContentPane().add(comboEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 161, -1, -1));

        btnContinuar.setBackground(new java.awt.Color(204, 0, 0));
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 302, -1, -1));

        jLabel1.setText("Egresos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 206, -1, -1));

        comboRojo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEAP", "COLA", " " }));
        getContentPane().add(comboRojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 203, -1, -1));
        getContentPane().add(txtMinEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 267, 51, -1));

        jLabel2.setText("Rango de tiempo de espera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 238, -1, -1));

        jLabel3.setText("De");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel4.setText("a");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));
        getContentPane().add(txtMaxEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 267, 63, -1));
        getContentPane().add(txtEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 203, 58, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
       
        tipoV = comboVerde.getSelectedItem().toString();
        tipoA = comboAmarillo.getSelectedItem().toString();
        tipoR = comboRojo1.getSelectedItem().toString();
        tipoE = comboEgresos.getSelectedItem().toString();
        
        if (this.txtVerde.getText().isEmpty() || this.txtAmarillo.getText().isEmpty() || this.txtRojo.getText().isEmpty() || this.txtMinEgresos.getText().isEmpty() ||
                this.txtMaxEgresos.getText().isEmpty() || this.txtEgresos.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Llene todos los campos");
       }
        else {
        
        ServicioEmergencia.Filas.filaRoja = new FilaPacientes(comboRojo1.getSelectedItem().toString());
        ServicioEmergencia.Filas.filaAmarilla  = new FilaPacientes(comboAmarillo.getSelectedItem().toString());
        ServicioEmergencia.Filas.filaVerde = new FilaPacientes(comboVerde.getSelectedItem().toString());
        ServicioEmergencia.Filas.filaEgresos  = new FilaPacientes(comboEgresos.getSelectedItem().toString());
        
        ServicioEmergencia.Filas.maxEgresos = Integer.parseInt(txtMaxEgresos.getText());
        ServicioEmergencia.Filas.minEgresos = Integer.parseInt(txtMinEgresos.getText());
        
        ServicioEmergencia.ServicioConsultorios.consultoriosRojos = new ListaConsultorios("ROJO",Integer.parseInt(txtRojo.getText()));
        ServicioEmergencia.ServicioConsultorios.consultoriosAmarillos = new ListaConsultorios("AMARILLO",Integer.parseInt(txtAmarillo.getText()));
        ServicioEmergencia.ServicioConsultorios.consultoriosVerdes = new ListaConsultorios("VERDE",Integer.parseInt(txtVerde.getText()));
        ServicioEmergencia.ServicioConsultorios.consultoriosEgresos = new ListaConsultorios("EGRESOS",Integer.parseInt(txtEgresos.getText()));
        
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> comboAmarillo;
    private javax.swing.JComboBox<String> comboEgresos;
    private javax.swing.JComboBox<String> comboRojo1;
    private javax.swing.JComboBox<String> comboVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmarillo;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerde;
    private javax.swing.JTextField txtAmarillo;
    private javax.swing.JTextField txtEgresos;
    private javax.swing.JTextField txtMaxEgresos;
    private javax.swing.JTextField txtMinEgresos;
    private javax.swing.JTextField txtRojo;
    private javax.swing.JTextField txtVerde;
    // End of variables declaration//GEN-END:variables
}
